/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.visao;

import br.com.controle.Compras;

/**
 *
 * @author kaio.veras
 */
public class TelaCompras extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCompras.class.getName());

    /**
     * Creates new form TelaCompras
     */
    public TelaCompras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLTextValorCompra = new javax.swing.JLabel();
        jTvalorCompra = new javax.swing.JTextField();
        jBcomprar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLvalorSemDesconto = new javax.swing.JLabel();
        jLvalorCompraDesconto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLTextValorCompra.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLTextValorCompra.setText("Digite o valor da compra:");

        jTvalorCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTvalorCompraActionPerformed(evt);
            }
        });

        jBcomprar.setText("Comprar");
        jBcomprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcomprarActionPerformed(evt);
            }
        });

        jLvalorSemDesconto.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLvalorSemDesconto.setForeground(new java.awt.Color(255, 0, 0));

        jLvalorCompraDesconto.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLvalorCompraDesconto.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLvalorSemDesconto)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLvalorCompraDesconto)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLTextValorCompra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTvalorCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jBcomprar, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLTextValorCompra)
                    .addComponent(jTvalorCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jBcomprar)
                .addGap(30, 30, 30)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLvalorSemDesconto)
                .addGap(18, 18, 18)
                .addComponent(jLvalorCompraDesconto)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTvalorCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTvalorCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTvalorCompraActionPerformed

    private void jBcomprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcomprarActionPerformed
        // TODO add your handling code here:
        Compras obj1 = new Compras();
        obj1.setValor(Double.valueOf(jTvalorCompra.getText()));
        
        jLvalorSemDesconto.setText("Valor da compra sem desconto: R$" + obj1.getValor());
        jLvalorCompraDesconto.setText(obj1.getDesconto());
    }//GEN-LAST:event_jBcomprarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaCompras().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBcomprar;
    private javax.swing.JLabel jLTextValorCompra;
    private javax.swing.JLabel jLvalorCompraDesconto;
    private javax.swing.JLabel jLvalorSemDesconto;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTvalorCompra;
    // End of variables declaration//GEN-END:variables
}
